ClassLength:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Documentation:
  Enabled: false

Eval:
  Enabled: false

FormatString:
  Enabled: false

HandleExceptions:
  Enabled: false

HashSyntax:
  Enabled: false

IndentationConsistency:
  Enabled: false

LineLength:
  Max: 323

MethodLength:
  Enabled: false

NilComparison:
  Enabled: false

NonNilCheck:
  Enabled: false

RaiseArgs:
  Enabled: true

RedundantReturn:
  Enabled: true

RedundantSelf:
  Enabled: true

RegexpLiteral:
  Enabled: false

RescueModifier:
  Enabled: true

ShadowingOuterLocalVariable:
  Enabled: false

SpaceAfterComma:
  Enabled: false

SpaceAroundOperators:
  Enabled: false

SpaceBeforeBlockBraces:
  Enabled: false

SpaceBeforeFirstArg:
  Enabled: false

SpaceInsideBlockBraces:
  Enabled: false

SpaceInsideBrackets:
  Enabled: false

SpecialGlobalVars:
  Enabled: false
