AccessorMethodName:
  Enabled: false

AlignParameters:
  Enabled: false

AssignmentInCondition:
  Enabled: false

BlockAlignment:
  Enabled: false

BlockNesting:
  Enabled: false

CaseEquality:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

ClassLength:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

BracesAroundHashParameters:
  Enabled: false

ColonMethodCall:
  Enabled: false

CommentAnnotation:
  Enabled: false

Documentation:
  Enabled: false

DoubleNegation:
  Enabled: false

EmptyLines:
  Enabled: false

EmptyLinesAroundBody:
  Enabled: false

Encoding:
  Enabled: false

EndAlignment:
  Enabled: false

Eval:
  Enabled: false

FinalNewline:
  Enabled: false

FormatString:
  Enabled: false

HandleExceptions:
  Enabled: false

HashSyntax:
  Enabled: false

IfUnlessModifier:
  Enabled: false

IndentationConsistency:
  Enabled: false

IndentArray:
  Enabled: false

IndentHash:
  Enabled: false

IndentationWidth:
  Enabled: false

Lambda:
  Enabled: false

LineEndConcatenation:
  Enabled: false

LineLength:
  Max: 323

Loop:
  Enabled: false

MethodCallParentheses:
  Enabled: false

MethodLength:
  Enabled: false

NegatedIf:
  Enabled: false

NegatedWhile:
  Enabled: false

NilComparison:
  Enabled: false

NonNilCheck:
  Enabled: false

ParenthesesAroundCondition:
  Enabled: false

RaiseArgs:
  Enabled: false

RedundantReturn:
  Enabled: false

RedundantSelf:
  Enabled: false

RegexpLiteral:
  Enabled: false

RescueModifier:
  Enabled: false

ShadowingOuterLocalVariable:
  Enabled: false

SpaceAfterComma:
  Enabled: false

SpaceAroundOperators:
  Enabled: false

SpaceBeforeBlockBraces:
  Enabled: false

SpaceBeforeFirstArg:
  Enabled: false

SpaceInsideBlockBraces:
  Enabled: false

SpaceInsideBrackets:
  Enabled: false

SpaceInsideHashLiteralBraces:
  Enabled: false

SpecialGlobalVars:
  Enabled: false

