ClassLength:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Documentation:
  Enabled: false

Eval:
  Enabled: false

FormatString:
  Enabled: false

HandleExceptions:
  Enabled: false

HashSyntax:
  Enabled: false

IndentationConsistency:
  Enabled: false

LineLength:
  Max: 323

MethodLength:
  Enabled: false

NilComparison:
  Enabled: true

NonNilCheck:
  Enabled: true

RaiseArgs:
  Enabled: true

RedundantReturn:
  Enabled: true

RedundantSelf:
  Enabled: true

RegexpLiteral:
  Enabled: true

RescueModifier:
  Enabled: true

ShadowingOuterLocalVariable:
  Enabled: true

SpaceAfterComma:
  Enabled: true

SpaceAroundOperators:
  Enabled: true

SpaceBeforeBlockBraces:
  Enabled: true

SpaceBeforeFirstArg:
  Enabled: true

SpaceInsideBlockBraces:
  Enabled: true

SpaceInsideBrackets:
  Enabled: true

SpecialGlobalVars:
  Enabled: true
