ClassLength:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Documentation:
  Enabled: false

Encoding:
  Enabled: false

EndAlignment:
  Enabled: false

Eval:
  Enabled: false

FormatString:
  Enabled: false

HandleExceptions:
  Enabled: false

HashSyntax:
  Enabled: false

IndentationConsistency:
  Enabled: false

IndentArray:
  Enabled: false

IndentHash:
  Enabled: false

IndentationWidth:
  Enabled: false

LineLength:
  Max: 323

MethodLength:
  Enabled: false

NilComparison:
  Enabled: true

NonNilCheck:
  Enabled: true

RaiseArgs:
  Enabled: true

RedundantReturn:
  Enabled: true

RedundantSelf:
  Enabled: true

RegexpLiteral:
  Enabled: true

RescueModifier:
  Enabled: true

ShadowingOuterLocalVariable:
  Enabled: true

SpaceAfterComma:
  Enabled: true

SpaceAroundOperators:
  Enabled: false

SpaceBeforeBlockBraces:
  Enabled: false

SpaceBeforeFirstArg:
  Enabled: false

SpaceInsideBlockBraces:
  Enabled: false

SpaceInsideBrackets:
  Enabled: false

SpecialGlobalVars:
  Enabled: false

