ClassLength:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Documentation:
  Enabled: false

Eval:
  Enabled: false

FormatString:
  Enabled: false

HandleExceptions:
  Enabled: false

HashSyntax:
  Enabled: false

IndentationConsistency:
  Enabled: false

LineLength:
  Max: 323

MethodLength:
  Enabled: false
