language: ruby

env:
  global:
    - secure: "BBg7RcixIsnmCQDkLuO9aVcqtCMJhnVfwZhc+az7UkSWGrs2biR4ArmMuhEA5UAp5gOfWdFk61OBNIJ7A+e22Czpi0msvlBCyDocaQR9Z1JQ8uDrsVohGd5+ir+fbo8cGw/Wr7Ol+KxLZC0TjlGnPtLa/J4MFomYjpF3JUCjnr8="
    - TEST_SUITE=test:unit
    - TEST_SUITE=test:integration

rvm:
  - 1.9.3
  - 2.1.0
  - ruby-head

before_install:
  - gem update --system
  - gem update bundler

before_script:
  - cp spec/data/.gooddata ~/

script: rake $TEST_SUITE
